### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Max12313** [Hazza3100/Discord-Twitch-Bot#1]
I’m Max and my friend told me about your discord server and everything and he sent me a GitHub link what lead to your code and I put everything. And my token for my bot but when I tried to run I need bot = commands.Bot(command_prefix=prefix, help_command=None) that’s the problem idk what’s wrong with is please help me. My discord is Gust123#8680 I sent you a friend request Or just help me fix is problem. By telling me what’s the code @Hazza3100

**Comment by Hazza3100** [comment]
Provide a error not the defining of bot

**Comment by Max12313** [comment]
Why dose line 37 code work for other people but not me what do you put

**Comment by Hazza3100** [comment]
Download the new one.

**Comment by Max12313** [comment]
You have a new one?

**Comment by Max12313** [comment]
Other problem

**Comment by Max12313** [comment]
@Hazza3100 Other problem/error now it says
Traceback (most recent call last):
File
"main.py", line 154, in 
bot.run)
TypeError: run() missing 1 required positional a
rgument:
"token'

**Comment by Max12313** [comment]
@Hazza3100

**Comment by Max12313** [comment]
@Hazza3100 A error it says 
   File "main.py", line 20
use_proxy = cfg[' use_proxy' ]
A
SyntaxError: invalid syntax

**Comment by Hazza3100** [comment]
> proxy' ]

You obviously changed the config to something that isn't "true" or "false" or you haven't download the config.
